name: CI

on:
  push:
    branches: [ main, lambda-refactor ]
  pull_request:
    branches: [ main, lambda-refactor ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Extract coverage percentage
      run: |
        COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct')
        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        echo "Coverage: $COVERAGE%"
        
    - name: Determine badge color
      run: |
        if (( $(echo "$COVERAGE >= 80" | bc -l) )); then
          echo "BADGE_COLOR=brightgreen" >> $GITHUB_ENV
        elif (( $(echo "$COVERAGE >= 60" | bc -l) )); then
          echo "BADGE_COLOR=yellow" >> $GITHUB_ENV
        else
          echo "BADGE_COLOR=red" >> $GITHUB_ENV
        fi
        
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: ${{ secrets.GIST_ID }}
        filename: museum-alert-api-coverage-badge.json
        label: Coverage
        message: ${{ env.COVERAGE }}%
        color: ${{ env.BADGE_COLOR }}
